mindstellar/Osclass

oc-includes/osclass/ItemActions.php, oc-includes/osclass/Logger/LogOsclass.php, oc-includes/osclass/Logger/Logger.php, oc-includes/osclass/WebThemes.php, oc-includes/osclass/classes/Scripts.php, oc-includes/osclass/core/View.php, oc-includes/osclass/core/caches/Object_Cache_apc.php, oc-includes/osclass/core/caches/Object_Cache_apcu.php, oc-includes/osclass/helpers/hItems.php, oc-includes/osclass/helpers/hPreference.php, oc-includes/osclass/helpers/hPremium.php, oc-includes/osclass/helpers/hUsers.php, oc-includes/osclass/utils.php
Merging experimental to master
=> Experimental

oc-includes/osclass/frm/Field.form.class.php
For more detail: https://forums.osclass.org/general-help/blank-drop-down-custom-field-in-search/
=> Blank drop-down in custom fields

oc-includes/osclass/classes/datatables/UsersDataTable.php
https://forums.osclass.org/3-7-x/data-is-the-same-as-update-data-in-admin-users/
=> fix User Registration Date

oc-includes/osclass/frm/Item.form.class.php
Osclass actually has "Make primary image" button when posting an item, but it's content is empty. There is no text.
https://github.com/navjottomer/Osclass/issues/35
=> Fix "Make primary image"

oc-includes/osclass/core/Session.php
https://forums.osclass.org/3-8-x-43/osclass-cookie-secure-flag/
=> Set Cookie Secure Param

oc-includes/osclass/helpers/hUtils.php
https://github.com/navjottomer/Osclass/issues/85
=> US and other location import fix 

oc-admin/ajax/ajax.php
=> Fix Market link

oc-includes/osclass/formatting.php
=> remove accents

.travis.yml
Currently Checking only 5.6,7.0,7.1,7.2,7.3
Sniffing is removed for now.
=> travis php syntax check.

oc-includes/osclass/helpers/hDefines.php
info is needed if is child theme only
=> web_theme_path

oc-includes/osclass/classes/Breadcrumb.php
Tested with Bender and Google structured data testing tool.
https://github.com/navjottomer/Osclass/issues/178
=> Upgraded breadcrumb to schema

oc-admin/login.php, oc-admin/themes/modern/functions.php, oc-includes/gui/admin/settings.php, oc-includes/gui/footer.php, oc-includes/gui/index.php, oc-includes/osclass/helpers/hUtils.php, oc-includes/osclass/install-location.php, oc-includes/osclass/install.php, oc-includes/osclass/upgrade-funcs.php
"navjottomer" to "mindstellar"
=> change repo url

oc-admin/themes/modern/appearance/index.php, oc-admin/themes/modern/plugins/index.php, oc-admin/themes/modern/tools/category.php, oc-admin/themes/modern/tools/locations.php, oc-includes/osclass/classes/AdminMenu.php
Including https://github.com/mindstellar/Osclass/issues/204
=> Minor admin fixes

oc-includes/osclass/controller/ajax.php
Reverts mindstellar/Osclass#215
You should not target the master branch.
@webmods-croatia please check pull-request target before approving it.
=> Revert "Supporting ajax url for theme developement"

oc-includes/osclass/helpers/hUsers.php
https://github.com/mindstellar/Osclass/issues/203
=> User access IP casted to int

oc-includes/osclass/classes/controller/CWebLogin.php
https://github.com/mindstellar/Osclass/issues/195
=> Before user recover hook

oc-includes/osclass/classes/Plugins.php
Faster isset .
in_array() will iterate over the entire array testing the value
=> Used hooks

oc-admin/controller/settings/advanced.php, oc-admin/controller/settings/comments.php, oc-admin/controller/settings/currencies.php, oc-admin/controller/settings/latestsearches.php, oc-admin/controller/settings/locations.php, oc-admin/controller/settings/mailserver.php, oc-admin/controller/settings/main.php, oc-admin/controller/settings/media.php, oc-admin/controller/settings/permalinks.php, oc-admin/controller/settings/spamnbots.php, oc-admin/settings.php, oc-includes/osclass/classes/controller/base/SecBaseModel.php, oc-includes/osclass/classes/controller/base/abstract/BaseModel.php
init_admin hook && AdminSecBaseModel constructor will run just once on
CAdminSettings => 
1. CAdminSettingsAdvanced,
2. CAdminSettingsComments,
3. CAdminSettingsCurrencies,
4. CAdminSettingsLatestSearches,
5. CAdminSettingsLocations
6. CAdminSettingsMailserver,
7. CAdminSettingsMain
8. CAdminSettingsMedia
9. CAdminSettingsPermalinks
10. CAdminSettingsSpamnBots
```php
public function __construct()
{
parent::__construct();
// check if is moderator and can enter to this page
if ($this->isModerator()
&& !in_array($this->page, osc_apply_filter('moderator_access', array(
'items',
'comments',
'media',
'login',
'admins',
'ajax',
'stats',
''
)), false)
) {
osc_add_flash_error_message(_m("You don't have enough permissions"), 'admin');
$this->redirectTo(osc_admin_base_url());
} …
```
=> Admin sec model

.gitignore, oc-includes/osclass/classes/utility/FileSystem.php, oc-includes/osclass/classes/utility/Upgrade.php, oc-includes/osclass/classes/utility/Utils.php, oc-includes/osclass/classes/utility/Zip.php, oc-includes/osclass/utils.php, oc-includes/osclass_autoloader.php
=> Auto update

oc-admin/themes/modern/items/frm.php, oc-includes/osclass/classes/actions/ItemActions.php, oc-includes/osclass/classes/form/ItemForm.php, oc-includes/osclass/classes/model/Item.php, oc-includes/osclass/helpers/hItems.php, oc-includes/osclass/installer/struct.sql
https://github.com/mindstellar/Osclass/issues/219
Tell me if I'm missing something.
Phone number validation helper was already there, I think it could be altered a bit...
=> Item phone number

oc-includes/osclass/functions.php, oc-includes/osclass/helpers/hUtils.php
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/mindstellar/osclass/issues).
=> Apply fixes from CodeFactor

oc-admin/themes/modern/items/settings.php, oc-includes/osclass/classes/actions/ItemActions.php, oc-includes/osclass/classes/controller/CWebItem.php, oc-includes/osclass/classes/controller/admin/CAdminItems.php, oc-includes/osclass/helpers/hPreference.php
https://github.com/mindstellar/Osclass/issues/211
=> Item moderation

oc-includes/osclass/classes/controller/admin/CAdminUsers.php, oc-includes/osclass/classes/datatables/UsersDataTable.php
https://github.com/mindstellar/Osclass/pull/232 but without the conflicts.
*I deleted the old repo in the meantime so I couldn't reopen the old PR*
=> Login as user
